version: '3.3'

services:

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - MSSQL_SA_PASSWORD=1
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
   
    ports:
      - "1433:1433"

  redis.data:
    image: redis:alpine
   
    ports:
      - "6379:6379"

  mongo.data:
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management-alpine
   
    ports:
      - "15672:15672"
      - "5672:5672"



